# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2018.1.5/bin/cmake/bin/cmake

# The command to remove a file.
RM = /opt/clion-2018.1.5/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/blank/CLionProjects/algorithms

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/blank/CLionProjects/algorithms

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2018.1.5/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2018.1.5/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blank/CLionProjects/algorithms/CMakeFiles /home/blank/CLionProjects/algorithms/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/blank/CLionProjects/algorithms/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named algorithms

# Build rule for target.
algorithms: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 algorithms
.PHONY : algorithms

# fast build rule for target.
algorithms/fast:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/build
.PHONY : algorithms/fast

List/List.o: List/List.cpp.o

.PHONY : List/List.o

# target to build an object file
List/List.cpp.o:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/List/List.cpp.o
.PHONY : List/List.cpp.o

List/List.i: List/List.cpp.i

.PHONY : List/List.i

# target to preprocess a source file
List/List.cpp.i:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/List/List.cpp.i
.PHONY : List/List.cpp.i

List/List.s: List/List.cpp.s

.PHONY : List/List.s

# target to generate assembly for a file
List/List.cpp.s:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/List/List.cpp.s
.PHONY : List/List.cpp.s

Queue/PriorityQueue.o: Queue/PriorityQueue.cpp.o

.PHONY : Queue/PriorityQueue.o

# target to build an object file
Queue/PriorityQueue.cpp.o:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Queue/PriorityQueue.cpp.o
.PHONY : Queue/PriorityQueue.cpp.o

Queue/PriorityQueue.i: Queue/PriorityQueue.cpp.i

.PHONY : Queue/PriorityQueue.i

# target to preprocess a source file
Queue/PriorityQueue.cpp.i:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Queue/PriorityQueue.cpp.i
.PHONY : Queue/PriorityQueue.cpp.i

Queue/PriorityQueue.s: Queue/PriorityQueue.cpp.s

.PHONY : Queue/PriorityQueue.s

# target to generate assembly for a file
Queue/PriorityQueue.cpp.s:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Queue/PriorityQueue.cpp.s
.PHONY : Queue/PriorityQueue.cpp.s

Queue/Queue.o: Queue/Queue.cpp.o

.PHONY : Queue/Queue.o

# target to build an object file
Queue/Queue.cpp.o:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Queue/Queue.cpp.o
.PHONY : Queue/Queue.cpp.o

Queue/Queue.i: Queue/Queue.cpp.i

.PHONY : Queue/Queue.i

# target to preprocess a source file
Queue/Queue.cpp.i:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Queue/Queue.cpp.i
.PHONY : Queue/Queue.cpp.i

Queue/Queue.s: Queue/Queue.cpp.s

.PHONY : Queue/Queue.s

# target to generate assembly for a file
Queue/Queue.cpp.s:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Queue/Queue.cpp.s
.PHONY : Queue/Queue.cpp.s

Solutions/Chapter_1/File.o: Solutions/Chapter_1/File.cpp.o

.PHONY : Solutions/Chapter_1/File.o

# target to build an object file
Solutions/Chapter_1/File.cpp.o:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Solutions/Chapter_1/File.cpp.o
.PHONY : Solutions/Chapter_1/File.cpp.o

Solutions/Chapter_1/File.i: Solutions/Chapter_1/File.cpp.i

.PHONY : Solutions/Chapter_1/File.i

# target to preprocess a source file
Solutions/Chapter_1/File.cpp.i:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Solutions/Chapter_1/File.cpp.i
.PHONY : Solutions/Chapter_1/File.cpp.i

Solutions/Chapter_1/File.s: Solutions/Chapter_1/File.cpp.s

.PHONY : Solutions/Chapter_1/File.s

# target to generate assembly for a file
Solutions/Chapter_1/File.cpp.s:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Solutions/Chapter_1/File.cpp.s
.PHONY : Solutions/Chapter_1/File.cpp.s

Stack/Stack.o: Stack/Stack.cpp.o

.PHONY : Stack/Stack.o

# target to build an object file
Stack/Stack.cpp.o:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Stack/Stack.cpp.o
.PHONY : Stack/Stack.cpp.o

Stack/Stack.i: Stack/Stack.cpp.i

.PHONY : Stack/Stack.i

# target to preprocess a source file
Stack/Stack.cpp.i:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Stack/Stack.cpp.i
.PHONY : Stack/Stack.cpp.i

Stack/Stack.s: Stack/Stack.cpp.s

.PHONY : Stack/Stack.s

# target to generate assembly for a file
Stack/Stack.cpp.s:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/Stack/Stack.cpp.s
.PHONY : Stack/Stack.cpp.s

UnorderedSet/USet.o: UnorderedSet/USet.cpp.o

.PHONY : UnorderedSet/USet.o

# target to build an object file
UnorderedSet/USet.cpp.o:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/UnorderedSet/USet.cpp.o
.PHONY : UnorderedSet/USet.cpp.o

UnorderedSet/USet.i: UnorderedSet/USet.cpp.i

.PHONY : UnorderedSet/USet.i

# target to preprocess a source file
UnorderedSet/USet.cpp.i:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/UnorderedSet/USet.cpp.i
.PHONY : UnorderedSet/USet.cpp.i

UnorderedSet/USet.s: UnorderedSet/USet.cpp.s

.PHONY : UnorderedSet/USet.s

# target to generate assembly for a file
UnorderedSet/USet.cpp.s:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/UnorderedSet/USet.cpp.s
.PHONY : UnorderedSet/USet.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/algorithms.dir/build.make CMakeFiles/algorithms.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... algorithms"
	@echo "... List/List.o"
	@echo "... List/List.i"
	@echo "... List/List.s"
	@echo "... Queue/PriorityQueue.o"
	@echo "... Queue/PriorityQueue.i"
	@echo "... Queue/PriorityQueue.s"
	@echo "... Queue/Queue.o"
	@echo "... Queue/Queue.i"
	@echo "... Queue/Queue.s"
	@echo "... Solutions/Chapter_1/File.o"
	@echo "... Solutions/Chapter_1/File.i"
	@echo "... Solutions/Chapter_1/File.s"
	@echo "... Stack/Stack.o"
	@echo "... Stack/Stack.i"
	@echo "... Stack/Stack.s"
	@echo "... UnorderedSet/USet.o"
	@echo "... UnorderedSet/USet.i"
	@echo "... UnorderedSet/USet.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

